### ISSUE TITLE
Update on application.

### ISSUE THREAD

**Issue by ethanfox** [Careswitch/careswitch-take-home#2]
When can I expect to hear back on the status of my application?

**Comment by KaiyuanMa** [comment]
2 weeks now, havent heard a thing

**Comment by pheuter** [comment]
Hi everyone,

Thank you all for your patience and for taking the time to complete your assignments. We understand that waiting for a response can be frustrating. Due to the high volume of applications, we can't always get around to responding to all assignments in a timely manner. If you don't hear back from us within a week of submission, it means we won't be moving forward with your application at this time.

Thank you for your understanding and interest in our team.
